export enum FunctionKey {
  GET_AGENTS = 'GET_AGENTS',
  GET_INBOXES = 'GET_INBOXES',

  GET_CHAT_CONVERSATION_PAGINATION = 'GET_CHAT_CONVERSATION_PAGINATION',

  GET_NODE_FILES = 'GET_NODE_FILES',
  GET_VR_FILES = 'GET_VR_FILES',
  GET_VR_FILES_SEARCH = 'GET_VR_FILES_SEARCH',
  GET_VR_SEARCH_SIMPLIFIED = 'GET_VR_SEARCH_SIMPLIFIED',
  SCAN_OLLAMA_MODELS = 'SCAN_OLLAMA_MODELS',
  GET_USER_SHEETS = 'GET_USER_SHEETS',
  GET_SHEET = 'GET_SHEET',
}
