name: Release dev

on:
  push:
    branches: [ main, agallardol/mobile-build ]

defaults:
  run:
    working-directory: ./

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use nx set shas
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: false
          registry-url: https://registry.npmjs.org
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          npm cache verify
          npm ci --no-audit --prefer-offline

      - name: Run NX build on shinkai-visor
        run: npx nx build shinkai-visor --skip-nx-cache --verbose
        env:
          VERSION: 0.0.0.${{github.run_number}}

      - name: Run NX build on shinkai-app-android
        run: |
          npx capacitor-set-version -v $VERSION -b $BUILD $APP_PATH
          npx nx build:android shinkai-app --verbose
        env:
          VERSION: 0.0.0
          BUILD: ${{github.run_number}}
          APP_PATH: ./apps/shinkai-app

      - uses: actions/upload-artifact@v3
        with:
          name: shinkai-visor
          path: dist/apps/shinkai-visor
          if-no-files-found: error
          retention-days: 5

      - uses: actions/upload-artifact@v3
        with:
          name: shinkai-app-android
          path: dist/apps/shinkai-app-android
          if-no-files-found: error
          retention-days: 5
