name: Sign test

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./

jobs:
  health-checks:
    runs-on: x86_64-pc-windows-msvc
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'shinkai-412316'


      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Download Jsign
        run: wget https://github.com/ebourg/jsign/releases/download/7.0/jsign-7.0.jar

      - name: Cert to file
        run: |
          echo -n "$EV_CODE_SIGNING_CERTIFICATE" | base64 --decode -o OS20241029372986.pem

      - name: Sign
        run: >
          java -jar jsign.jar \
              --storetype GOOGLECLOUD \
              --storepass "$(gcloud auth print-access-token)" \
              --keystore "projects/shinkai-412316/locations/us/keyRings/shinkai-apps" \
              --alias "EVCodeSigning" \
              --certfile "OS20241029372986.pem" \
              --tsmode RFC3161 \
              --tsaurl http://timestamp.globalsign.com/tsa/r6advanced1 \
              package.json
